version: "3.9"

services:
  php-env:
    build: .
    volumes:
      - ./Website:/var/www/html
    ports:
      - 9000:80

  maria_db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1